repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.8.0
    hooks:
      - id: isort
        stages: [commit]

  - repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
      - id: black
        stages: [commit]

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        description: "This hook checks for pylint errors using the active virtual environment."
        stages: [push]
        entry: pylint
        args:
          - --errors-only
        language: python
        verbose: true
        types: [python]
